# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170127_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('list', 'text')]),
        ),
    ]
